# Model selection for mad1endog

In [56]:
using JLD2, Plots, LaTeXStrings, DataFrames

Iterate over the possible model values of $S$ and $R$. This gives the orders of the acceptance rates in `ABCoutputs` that follows.

In [48]:
hypars = [[i,j] for i in 2:4 for j in 1:4];

In [54]:
labels = ["S=$(i), R=$(j)" for i in 2:4 for j in 1:4]

12-element Vector{String}:
 "S=2, R=1"
 "S=2, R=2"
 "S=2, R=3"
 "S=2, R=4"
 "S=3, R=1"
 "S=3, R=2"
 "S=3, R=3"
 "S=3, R=4"
 "S=4, R=1"
 "S=4, R=2"
 "S=4, R=3"
 "S=4, R=4"

Import all the outputs of the ABC sims.

In [36]:
ABCoutputs = [load("./mad1endog/S$(i)R$(j).jld2","ABC") for i in 2:4 for j in 1:4];

┌ Warning: type GpABC.SimulatedABCSMCOutput does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/ryhNR/src/data/reconstructing_datatypes.jl:495
┌ Warning: type GpABC.SimulatedABCSMCOutput does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/ryhNR/src/data/reconstructing_datatypes.jl:495
┌ Warning: type GpABC.SimulatedABCSMCOutput does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/ryhNR/src/data/reconstructing_datatypes.jl:495
┌ Warning: type GpABC.SimulatedABCSMCOutput does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/ryhNR/src/data/reconstructing_datatypes.jl:495
┌ Warning: type GpABC.SimulatedABCSMCOutput does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/ryhNR/src/data/reconstructing_datatypes.jl:495
┌ Warning: type GpABC.SimulatedABCSMCOutput does not exist in workspace; reconstructing
└ @ JLD2 ~/.julia/packages/JLD2/ryhNR/src/data/reconstructing_datatypes.jl:49

In [39]:
ABCoutputs;

In [81]:
acc_rates = [ABCoutputs[i].n_accepted[end]/ABCoutputs[i].n_tries[end] for i in 1:length(ABCoutputs)];
acc_rates[1] = 1e-5; # S2R2 returned 0 accepted particles

In [83]:
acc_rates

12-element Vector{Float64}:
 1.0e-5
 1.0e-5
 1.0e-5
 1.0e-5
 0.0002
 0.00755
 0.07454342154304883
 0.07454342154304883
 0.00088
 0.05173841059602649
 0.021827389007726895
 0.019445038598401618

In [84]:
bayes_table = ones(length(ABCoutputs),length(ABCoutputs));
for i in 1:length(ABCoutputs)
    for j in 1:length(ABCoutputs)
        bayes_table[i,j] = acc_rates[i]/acc_rates[j]
    end
end
bayes_table

12×12 Matrix{Float64}:
    1.0      1.0      1.0      1.0   …  0.00019328  0.00045814  0.00051427
    1.0      1.0      1.0      1.0      0.00019328  0.00045814  0.00051427
    1.0      1.0      1.0      1.0      0.00019328  0.00045814  0.00051427
    1.0      1.0      1.0      1.0      0.00019328  0.00045814  0.00051427
   20.0     20.0     20.0     20.0      0.0038656   0.0091628   0.0102854
  755.0    755.0    755.0    755.0   …  0.145926    0.345896    0.388274
 7454.34  7454.34  7454.34  7454.34     1.44078     3.41513     3.83354
 7454.34  7454.34  7454.34  7454.34     1.44078     3.41513     3.83354
   88.0     88.0     88.0     88.0      0.0170086   0.0403163   0.0452558
 5173.84  5173.84  5173.84  5173.84     1.0         2.37034     2.66075
 2182.74  2182.74  2182.74  2182.74  …  0.42188     1.0         1.12252
 1944.5   1944.5   1944.5   1944.5      0.375834    0.890855    1.0

In [85]:
bayes_df = DataFrame([[] for i in 1:length(labels)], labels)
for i in 1:length(labels)
    push!(bayes_df,bayes_table[i,:])
end

In [86]:
bayes_df

12×12 DataFrame
 Row │ S=2, R=1  S=2, R=2  S=2, R=3  S=2, R=4  S=3, R=1  S=3, R=2   S=3, R=3   ⋯
     │ Any       Any       Any       Any       Any       Any        Any        ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 1.0       1.0       1.0       1.0       0.05      0.0013245  0.00013415 ⋯
   2 │ 1.0       1.0       1.0       1.0       0.05      0.0013245  0.00013415
   3 │ 1.0       1.0       1.0       1.0       0.05      0.0013245  0.00013415
   4 │ 1.0       1.0       1.0       1.0       0.05      0.0013245  0.00013415
   5 │ 20.0      20.0      20.0      20.0      1.0       0.0264901  0.002683   ⋯
   6 │ 755.0     755.0     755.0     755.0     37.75     1.0        0.101283
   7 │ 7454.34   7454.34   7454.34   7454.34   372.717   9.8733     1.0
   8 │ 7454.34   7454.34   7454.34   7454.34   372.717   9.8733     1.0
   9 │ 88.0      88.0      88.0      88.0      4.4       0.116556   0.0118052  ⋯
  10 │ 5173.84   5173.84   5173.84   5173.84   258.692   6.85277    0.694071
  11 │ 2182.74   2182.74   2182.74   2182.74   109.137   2.89104    0.292814
  12 │ 1944.5    1944.5    1944.5    1944.5    97.2252   2.5755     0.260855
                                                               5 columns omitted

In [89]:
model_sel_tab = convert(Matrix{Any},zeros(length(ABCoutputs),length(ABCoutputs)));
for i in 1:length(ABCoutputs)
    for j in 1:length(ABCoutputs)
        if bayes_table[i,j]>10
            model_sel_tab[i,j] = "row"
        elseif bayes_table[i,j]<0.1
            model_sel_tab[i,j] = "col"
        end
    end
end
model_sel_tab;

In [90]:
model_sel_df = DataFrame([[] for i in 1:length(labels)], labels)
for i in 1:length(labels)
    push!(model_sel_df,model_sel_tab[i,:])
end
model_sel_df

12×12 DataFrame
 Row │ S=2, R=1  S=2, R=2  S=2, R=3  S=2, R=4  S=3, R=1  S=3, R=2  S=3, R=3  S ⋯
     │ Any       Any       Any       Any       Any       Any       Any       A ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │ 0.0       0.0       0.0       0.0       col       col       col       c ⋯
   2 │ 0.0       0.0       0.0       0.0       col       col       col       c
   3 │ 0.0       0.0       0.0       0.0       col       col       col       c
   4 │ 0.0       0.0       0.0       0.0       col       col       col       c
   5 │ row       row       row       row       0.0       col       col       c ⋯
   6 │ row       row       row       row       row       0.0       0.0       0
   7 │ row       row       row       row       row       0.0       0.0       0
   8 │ row       row       row       row       row       0.0       0.0       0
   9 │ row       row       row       row       0.0       0.0       col       c ⋯
  10 │ row       row       row       row       row       0.0       0.0       0
  11 │ row       row       row       row       row       0.0       0.0       0
  12 │ row       row       row       row       row       0.0       0.0       0
                                                               5 columns omitted